version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      kotlin:
        patterns:
          - "org.jetbrains.kotlin.*"
          - "com.google.devtools.ksp"
          - "kotlin*"
          - "*kotlin*"
      spring:
        patterns:
          - "*spring*"
      junit-jupiter:
        patterns:
          - "junit*"
          - "*junit*"
          - "*junit*"
          - "*jupiter"
          - "jupiter*"
          - "*jupiter*"
