name: Image Sizer PR
on:
  pull_request:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Prepare environment
        run: wget https://download.java.net/openjdk/jdk8u41/ri/openjdk-8u41-b04-linux-x64-14_jan_2020.tar.gz -P /tmp &&
          tar xf /tmp/openjdk-8u41-b04-linux-x64-14_jan_2020.tar.gz -C ~/

      - name: Preparing Folder
        run: ls -d /opt/hostedtoolcache/Java_Adopt_jdk/17.0*/x64/../ | xargs -I {}  mkdir {}/lib

      - name: Preparing tools.jar
        run: ls -d /opt/hostedtoolcache/Java_Adopt_jdk/17.0*/x64/../lib | sudo xargs cp ~/java-se-8u41-ri/lib/tools.jar

      - name: Build and Test Maven
        run: mvn clean install

      - name: Install Snyk
        run: npm i -g snyk

      - name: Build NPM
        run: make build-npm

      - name: Test NPM
        run: make test-npm

      - name: Security NPM
        run: make security-npm
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
