name: xml-adder-pull_request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:

     runs-on: ubuntu-latest

     steps:
     - uses: actions/checkout@v3
     - name: Set up JDK 11
       uses: actions/setup-java@v3
       with:
         java-version: '11'
         distribution: 'adopt'

     - name: Setup Gradle
       uses: gradle/gradle-build-action@v2

     - name: Grant execute permission for gradlew
       run: chmod +x gradlew

     - name: Creates properties
       run: touch local.properties

     - name: Build
       run: ./gradlew clean build test jacocoTestReport -i
