name: json-to-builder-pattern-pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle Wrapper
        run: gradle wrapper
      - name: Gradle Build
        run: ./gradlew clean test build jacocoTestReport
