name: json-to-builder-pattern

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'

      - name: Gradle Wrapper
        run: gradle wrapper
      - name: Gradle Build
        run: ./gradlew clean test build
      - name: JaCoco Report
        run: ./gradlew build jacocoTestReport
      - name: Coveralls Coverage
        run: ./gradlew build jacocoTestReport coveralls
        env:
           COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
      - name: Codecov Coverage
        run: bash <(curl -s https://codecov.io/bash)
        env:
           CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      - name: Codacy Coverage
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -l Java $(find **/jacoco*.xml -printf '-r %p ')
        env:
           CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
