name: performance-projects

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build Test
      run: 	./gradlew clean build test jacocoTestReport -i

    - name: Build Test
      run: ./gradlew -i
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
