name: performance-parsers-pull-request

on:
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - uses: actions/checkout@v2
        - name: Set up JDK 17
          uses: actions/setup-java@v2
          with:
            java-version: '17'
            distribution: 'adopt'

        - name: Prepare environment
          run: wget https://download.java.net/openjdk/jdk8u41/ri/openjdk-8u41-b04-linux-x64-14_jan_2020.tar.gz -P /tmp &&
              tar xf /tmp/openjdk-8u41-b04-linux-x64-14_jan_2020.tar.gz -C ~/

        - name: Preparing tools.jar
          run: sudo cp ~/java-se-8u41-ri/lib/tools.jar /opt/hostedtoolcache/Java_Adopt_jdk/17.0.2-8/x64/../lib/tools.jar

        - name: Build and Test
          run: mvn clean install jacoco:prepare-agent package jacoco:report
