name: SAARP Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'adopt'

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v3

    - name: Build and Test API
      run: cd string-paradigm-api && gradle clean build &&gradle assemble test publishToMavenLocal

    - name: Build and Expression API
      run: cd string-paradigm-expression-api && gradle clean build &&gradle assemble test publishToMavenLocal

    - name: Build and Expression No Wrapper API
      run: cd string-paradigm-expression-no-wrapper && gradle clean build &&gradle assemble test publishToMavenLocal

    - name: Build Complete
      run: gradle clean build test publishToMavenLocal && gradle dependencies
      env:
         COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
         CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}
         CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
